[platformio]
src_dir = wifi-water-monitor

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_port = COM9
monitor_port = COM9
build_flags =
  -I.
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

;
; OTA Section
;

; [env:esp32-c3-devkitm-1]
; platform = espressif32
; board = esp32-c3-devkitm-1
; framework = arduino
; monitor_speed = 115200
; upload_protocol = espota
; upload_port = 192.168.15.13
; upload_flags =
;   --auth=CHANGE-THIS-OTA-PASSWORD
; monitor_port = COM9
; build_flags =
;   -I.
;   -DARDUINO_USB_MODE=1
;   -DARDUINO_USB_CDC_ON_BOOT=1